# Generated by Django 4.2.15 on 2024-08-13 03:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BulkProduct",
        ),
        migrations.DeleteModel(
            name="FixedAmountDiscount",
        ),
        migrations.DeleteModel(
            name="PercentageDiscount",
        ),
        migrations.DeleteModel(
            name="SeasonalProduct",
        ),
    ]
